apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: infra
data:
  Caddyfile: |
    n8n.devops.vlxx.fr {
      reverse_proxy n8n.devops.svc.cluster.local:5678
    }

    dozzle.devops.vlxx.fr {
      reverse_proxy dozzle.devops.svc.cluster.local:8080
    }
