apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: infra
data:
  Caddyfile: |
    n8n.co.vlxx.fr {
      reverse_proxy n8n.devops.svc.cluster.local:5678
    }
    dozzle.co.vlxx.fr {
      reverse_proxy dozzle.devops.svc.cluster.local:8080
    }
    status.co.vlxx.fr {
      reverse_proxy uptime-kuma.devops.svc.cluster.local:3001
    }
    grafana.co.vlxx.fr {
      reverse_proxy grafana.devops.svc.cluster.local:3000
    }
    prometheus.co.vlxx.fr {
      reverse_proxy prometheus.devops.svc.cluster.local:9090
    }
