apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockHostNamespaces
metadata:
  name: block-host-namespaces
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "DaemonSet", "StatefulSet", "ReplicaSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - infra