apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: apps
spec:
  containers:
    - name: api
      image: ghcr.io/al4-esgi/devops:latest
  imagePullSecrets:
    - name: ghcr-pull-secret
  ports:
    - port: 3002
      targetPort: 3000
