apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops
type: Opaque
data:
  # Valeurs en base64 — modifier avec : echo -n "valeur" | base64
  POSTGRES_USER: cG9zdGdyZXM=      # postgres
  POSTGRES_PASSWORD: Y2hhbmdlbWU=  # changeme — À MODIFIER
  POSTGRES_DB: bjhuX2Ri            # n8n_db
